In [42]:
import pandas as pd

In [43]:
# Dataset from https://collegescorecard.ed.gov/data/
df = pd.read_csv('/Users/jessicabenitez/Documents/GitHub/college-rec/College_Scorecard_Raw_Data_04082024/MERGED2022_23_PP.csv', 
                 encoding='latin-1')
df.head(10)

/var/folders/4l/q8fyjl614w1567jd1msnhymw0000gn/T/ipykernel_6672/830166818.py:2: DtypeWarning: Columns (9,1725,1726,1727,1728,1729,1743,1815,1816,1817,1818,1823,1824,1830,1831,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1909,1910,1911,1912,1913,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1983,1984,2403,2404,2495,2496,2497,2498,2499,2500,2501,2502,2503,2504,2505,2506,2507,2508,2509,2510,2511,2512,2513,2514,2515,2516,2517,2518,2519,2520,2521,2522,2523,2524,2525,2526,2527,2528,2529,2530,3215,3231,3235,3236) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/jessicabenitez/Documents/GitHub/college-rec/College_Scorecard_Raw_Data_04082024/MERGED2022_23_PP.csv',

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,DCS_PELL_LOAN,PCTPELL_DCS_POOLED_SUPP,PCTFLOAN_DCS_POOLED_SUPP,DCS_PELL_LOAN_POOLED,POOLYRS_DCS,SATVR50,SATMT50,ACTCM50,ACTEN50,ACTMT50
0,100654,100200.0,1002.0,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www.aamu.edu/admissions-aid/tuition-fees/net-p...,...,5094.0,0.6553,0.5365,5094.0,1.0,470.0,450.0,17.0,16.0,16.0
1,100663,105200.0,1052.0,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu/,https://tcc.ruffalonl.com/University of Alabam...,...,13284.0,0.3374,0.4214,13284.0,1.0,650.0,650.0,27.0,27.0,25.0
2,100690,2503400.0,25034.0,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,https://www.amridgeuniversity.edu/,https://www2.amridgeuniversity.edu:9091/,...,251.0,0.7769,0.5896,251.0,1.0,NaN,NaN,NaN,NaN,NaN
3,100706,105500.0,1055.0,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu/,finaid.uah.edu/,...,7360.0,0.2235,0.3511,7360.0,1.0,650.0,685.0,26.0,28.0,26.0
4,100724,100500.0,1005.0,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu/,www.alasu.edu/cost-aid/tuition-costs/net-price...,...,3495.0,0.6984,0.768,3495.0,1.0,480.0,455.0,18.0,17.0,16.0
5,100751,105100.0,1051.0,The University of Alabama,Tuscaloosa,AL,35487-0100,Southern Association of Colleges and Schools C...,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,...,30725.0,0.1843,0.3494,30725.0,1.0,630.0,630.0,28.0,28.0,26.0
6,100760,100700.0,1007.0,Central Alabama Community College,Alexander City,AL,35010,Southern Association of Colleges and Schools C...,www.cacc.edu/,https://www.cacc.edu/net-price-calculator/,...,940.0,0.5011,0.2532,940.0,1.0,NaN,NaN,NaN,NaN,NaN
7,100812,100800.0,1008.0,Athens State University,Athens,AL,35611,Southern Association of Colleges and Schools C...,www.athens.edu/,www.athens.edu/financial-aid/net-price-calcula...,...,2511.0,0.4205,0.4389,2511.0,1.0,NaN,NaN,NaN,NaN,NaN
8,100830,831000.0,8310.0,Auburn University at Montgomery,Montgomery,AL,36117-3596,Southern Association of Colleges and Schools C...,www.aum.edu/,www.aum.edu/current-students/financial-informa...,...,3742.0,0.5011,0.5329,3742.0,1.0,540.0,530.0,20.0,21.0,18.0
9,100858,100900.0,1009.0,Auburn University,Auburn,AL,36849,Southern Association of Colleges and Schools C...,www.auburn.edu/,https://www.auburn.edu/admissions/costcalc/fre...,...,24782.0,0.1261,0.2804,24782.0,1.0,650.0,650.0,27.0,28.0,26.0

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6484 entries, 0 to 6483
Columns: 3244 entries, UNITID to ACTMT50
dtypes: float64(2703), int64(13), object(528)
memory usage: 160.5+ MB

In [45]:
# showing duplicates
df.duplicated(subset='INSTNM').sum()

127

There are 127 duplicate rows

In [46]:
df.drop(['INSTURL', 'NPCURL', 'SATVR50', 'SATMT50', 'ACTCM50', 'ACTEN50', 'ACTMT50', 'PCTPELL_DCS', 'PCTFLOAN_DCS',
         'DCS_PELL_LOAN', 'PCTPELL_DCS_POOLED_SUPP', 'PCTFLOAN_DCS_POOLED_SUPP', 'DCS_PELL_LOAN_POOLED', 'POOLYRS_DCS',
         'OMAWDP8_NOPELL_FIRSTTIME', 'OMENRUP_NOPELL_FIRSTTIME', 'OMENRYP_NOPELL_NOTFIRSTTIME', 'OMENRAP_NOPELL_NOTFIRSTTIME',
         'OMAWDP8_NOPELL_NOTFIRSTTIME', 'OMENRUP_NOPELL_NOTFIRSTTIME', 'OMACHT8_NOPELL_ALL', 'OMACHT8_NOPELL_FIRSTTIME',
         'OMACHT8_NOPELL_NOTFIRSTTIME', 'BBRR4_PP_NOMALE_DISCHARGE', 'CONTROL_PEPS', 'ADM_RATE_SUPP', 'OMENRYP_NOPELL_ALL',
         'OMENRAP_NOPELL_ALL', 'OMAWDP8_NOPELL_ALL', 'OMENRUP_NOPELL_ALL', 'OMENRYP_NOPELL_FIRSTTIME', 'OMENRAP_NOPELL_FIRSTTIME',
         ], inplace=True, axis=1)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6484 entries, 0 to 6483
Columns: 3212 entries, UNITID to ADDR
dtypes: float64(2678), int64(13), object(521)
memory usage: 158.9+ MB

In [48]:
df.head(10)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,SCH_DEG,HCM2,...,BBRR4_PP_MALE_DISCHARGE,BBRR4_PP_NOMALE_N,BBRR4_PP_NOMALE_DFLT,BBRR4_PP_NOMALE_DLNQ,BBRR4_PP_NOMALE_FBR,BBRR4_PP_NOMALE_DFR,BBRR4_PP_NOMALE_NOPROG,BBRR4_PP_NOMALE_MAKEPROG,BBRR4_PP_NOMALE_PAIDINFULL,ADDR
0,100654,100200.0,1002.0,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,NaN,0,...,PS,PS,PS,PS,PS,PS,PS,PS,PS,4900 Meridian Street
1,100663,105200.0,1052.0,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,NaN,0,...,PS,PS,PS,PS,PS,PS,PS,PS,PS,Administration Bldg Suite 1070
2,100690,2503400.0,25034.0,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,NaN,0,...,PS,PS,PS,PS,PS,PS,PS,PS,PS,1200 Taylor Rd
3,100706,105500.0,1055.0,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,NaN,0,...,PS,PS,PS,PS,PS,PS,PS,PS,PS,301 Sparkman Dr
4,100724,100500.0,1005.0,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,NaN,0,...,PS,PS,PS,PS,PS,PS,PS,PS,PS,915 S Jackson Street
5,100751,105100.0,1051.0,The University of Alabama,Tuscaloosa,AL,35487-0100,Southern Association of Colleges and Schools C...,NaN,0,...,PS,PS,PS,PS,PS,PS,PS,PS,PS,739 University Blvd
6,100760,100700.0,1007.0,Central Alabama Community College,Alexander City,AL,35010,Southern Association of Colleges and Schools C...,NaN,0,...,PS,PS,PS,PS,PS,PS,PS,PS,PS,1675 Cherokee Rd
7,100812,100800.0,1008.0,Athens State University,Athens,AL,35611,Southern Association of Colleges and Schools C...,NaN,0,...,PS,PS,PS,PS,PS,PS,PS,PS,PS,300 N Beaty St
8,100830,831000.0,8310.0,Auburn University at Montgomery,Montgomery,AL,36117-3596,Southern Association of Colleges and Schools C...,NaN,0,...,PS,PS,PS,PS,PS,PS,PS,PS,PS,7440 East Drive
9,100858,100900.0,1009.0,Auburn University,Auburn,AL,36849,Southern Association of Colleges and Schools C...,NaN,0,...,PS,PS,PS,PS,PS,PS,PS,PS,PS,"Auburn, Alabama"